# Generated by Django 4.1.7 on 2023-04-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookhub", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
