# Generated by Django 4.1.7 on 2023-04-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookhub", "0002_bookcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookcategory",
            name="name",
            field=models.CharField(db_column="name", max_length=100),
        ),
    ]
